### ISSUE TITLE
Upload & store user code changes as commits

### ISSUE THREAD

**Issue by amitkumar** [amitkumar/code-and-craft#2]

**Comment by jazzyjackson** [comment]
The first idea for the architecture of this is: 

1. the server config is given a directory to use for client commits.
2. Maybe it checks that there's a .git directory and creates one if there's not.
3. On user connection, client will ask for username, and then redirect to the gifloopcoder interface
4. on that res.redirect there is a cookie with that username, so the server will know what to do with future post requests, and can also ignore requests that don't have a cookie. Alternately this could all be done with socket.io, but we'll be posting text and binary blobs, and that's what HTTP is for. [ this could also be a place where the client grabs the latest input values before actually compiling. TBD ]
5. A click listener is attached to the compiler button. On compile, the code and parameters are posted to the server. TBD: does the client also compile a gif to post to the git repo? Is it possible to render the gif as a sort of background process to not interrupt the realtime playback? Maybe the canvas and its changes can be duplicated to a hidden canvas used for gif rendering.... 
6. The server checks the cookie, creates a directory if one doesn't exist, and overwrites any existing files with the new props given by the POST req. A souce.txt and a config.json object will be the archive data to potentially recreate. Having the gif committed would make replaying all the changes way simpler.
7. Once all the files are saved perform a git commit. Should probably pass two commands at once, like, "git add user22/source.txt user22/config.json ; git commit -m "automaticcommit" so that each commit only represents one user's changes, even when lots of file operations are happening on the server.
8. Done! Now the git repo reflects many changes in many directories, one commit at a time.
